USE [s15guest38]
GO
/****** Object:  Table [dbo].[Gift]    Script Date: 4/25/2015 2:58:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Gift](
	[Gift_id] [int] IDENTITY(1,1) NOT NULL,
	[Raffle_id] [int] NOT NULL,
	[Gift] [varchar](100) NOT NULL,
 CONSTRAINT [PK_Gift] PRIMARY KEY CLUSTERED 
(
	[Gift_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[Gift]  WITH CHECK ADD  CONSTRAINT [FK_Raffle_Gift] FOREIGN KEY([Raffle_id])
REFERENCES [dbo].[Raffle] ([Raffle_id])
GO
ALTER TABLE [dbo].[Gift] CHECK CONSTRAINT [FK_Raffle_Gift]
GO
